backend:
  name: github
  repo: Bearmeadow92/NextGenBlog
  branch: main

media_folder: "images"
public_folder: "/images"

# Better interface settings
editor:
  preview: true
show_preview_links: true
display_url: https://nextgentechnologist.com

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "Enter your post title"}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD", hint: "Publication date"}
      - {label: "Description", name: "description", widget: "text", hint: "Brief summary for the blog list"}
      - {label: "Body", name: "body", widget: "markdown"}